### ISSUE TITLE
Volume definition needs to done better

### ISSUE THREAD

**Issue by pradeepto** [surajssd/opencomposition#14]
Improve the way volume definition is done, size is not common to everything it's only in pvc.

**Comment by kadel** [comment]
There is a bit more issues with how are volumes done currently.

I think that top level "persistentVolume" should be based on PersistentVolumeClaim and not on Volume.

**Comment by kadel** [comment]
This is how I think handling persistent storage should look like.

full example
```yaml
name: database
containers:
# pod spec
- image: mariadb:10
  volumeMounts:
  - name: vol1
    mountPath: /var/lib/mysql
volumes:
  - name: vol1
    persistentVolumeClaim:
       claimName: vol1

persistentVolumes:
# PersitentVolumeClaimSpec
- name: vol1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

with shortcuts
```yaml
name: database
containers:
- image: mariadb:10
  volumeMounts:
  - name: vol1
    mountPath: /var/lib/mysql

persistentVolumes:
- name: vol1
  size: 8Gi # shortcut for specifying 'requst.storage'
```

If there is no matching `volume` for `volumeMount`, `volume` is created automatically with the same name and the same name is also used to attach `volume` to 'persistentVolumeClaim`
