### ISSUE TITLE
Thoughts on refactoring Services in the spec

### ISSUE THREAD

**Issue by containscafeine** [surajssd/opencomposition#18]
Okay, so this is the data that the ServiceSpec in Kubernetes contains -

- `Name`
- `Ports`
- `Selector`
- `ClusterIP`
- `Type` - one of `ExternalName`, `ClusterIP`, `NodePort`, and `LoadBalancer`
- `ExternalIPs`
- `SessionAffinity`
- `LoadBalancerIP`
- `LoadBalancerSourceRanges`
- `ExternalName`

Now, I understand that a service will be applied to the pods with the given selector, and yes, this needs to be defined outside `containers:`, so I think that the service spec should be defined at the root level.

- We get rid of `Selector`, because well, we are defining the service with a given pod, so the selected happens to be that automatically.
- We get rid of `Name` because we don't need it anywhere, and we can name it ourselves, like we used to do with containers in OpenCompose.
- Rename `Type` to something more generic like `ExposeType` or `AccessPolicy` or `AccessType`, or something better than this which can be understood without the context of Kubernetes.

An example file would look like -

```yaml
name: web
replicas: 1
containers:
- image: wordpress:4
  env:
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
  - name: WORDPRESS_DB_USER
    value: wordpress
accessType: NodePort
ports:
- port: 8080
  targetPort: 80
```
