### ISSUE TITLE
A better way to define Service ports

### ISSUE THREAD

**Issue by containscafeine** [surajssd/opencomposition#19]
The way Kubernetes' ServiceSpec allows describing Ports is something like this -

```yaml
services:
- name: wordpress
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: UDP
```

We can also provide an alternative _shortcut_ way to do this by using a syntax like -

```yaml
services:
- name: wordpress
  type: LoadBalancer
  ports:
  - 8080:80/udp
```

**Comment by pradeepto** [comment]
Will this not make tooling difficult and perhaps induce string magic?

**Comment by kadel** [comment]
you are overwriting already existing 'ports'. Shortcuts can't do that. We have to keep the original way of defining things untouched.

**Comment by containscafeine** [comment]
@pradeepto -
> Will this not make tooling difficult and perhaps induce string magic?

Yes, the tooling will be difficult but that is an implementation detail that we can take care of.
Yes, this introduces string magic, but how else do we want to implement more intuitive shortcuts?

@kadel -
> We can use a shortcut like this, but it has to be named differently. Something that is not already in ServiceSpec

Agree, we can have a different field name for this, we can carry the `...Ref` convention here

```yaml
services:
- name: wordpress
  type: LoadBalancer
  portRef:
  - 8080:80/udp
```
