### ISSUE TITLE
Only health at container level

### ISSUE THREAD

**Issue by surajssd** [surajssd/opencomposition#23]
Right now pod spec allows you to do both `livenessProbe` and `readinessProbe` and since both the fields represent the same data strcuture behind the scene which is called `probes`.

So a container will look like the following:

```yaml
containers:
- image: wordpress:4
  health:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 120
    timeoutSeconds: 5
```

the pod that is generated out of this will look like this:

```yaml
containers:
- image: wordpress:4
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 120
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 120
    timeoutSeconds: 5
```

So essentially you just specify `health` field which is `probe` type and then it is populated into `readinessProbe` and `livenessProbe` in the output. But if user provides the fields `readinessProbe` or `livenessProbe` explicitly then `health` field is ignored! Those fields are used directly.
